### ISSUE TITLE
an app err

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#17]
```py
Task exception was never retrieved
future: <Task finished coro=<Application.done() done, defined at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py:237> exception=AttributeError("'NoneType' object has no attribute 'version_tag'",)>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 239, in done
    async for data in self.work():
  File "<ipython-input-43-7fb1a30a2d3e>", line 6, in work
    x,y = await app.done()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 243, in done
    self.saveRecord(result)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 216, in saveRecord
    self.status['current_record'] = self.newRecord()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 193, in newRecord
    title=self.record_title(),
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 93, in record_title
    version = '%s.%d' % (self.__AppData__.version_tag,
AttributeError: 'NoneType' object has no attribute 'version_tag'
```

**Comment by feihoo87** [comment]
Paste your code here, not just error message.

**Comment by Lagikna** [comment]
已解决！
