### ISSUE TITLE
make_figure_for_app and display err

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#24]
```py
import lab
import numpy as np

app = lab.make_app('TestApp').sweep([
    ('x', np.linspace(0, 1, 11))
])
lab.make_figure_for_app(app)
app.run()
```

```py
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
Exception in callback draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79
handle: <Handle draw.<locals>.callback(figure=<lab._plot.No...000000539CA58>)(<Task finishe...le anymore',)>) at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py:79>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 80, in callback
    img, width, height = future.result()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_plot.py", line 59, in make_image_in_process
    functools.partial(make_image, func, data, **kwds))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```
```py
results = lab.query()
results.display()
print('%d results found.' % results.count())
```
```py
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-8ba9aa32f2d0> in <module>()
      1 results = lab.query()
----> 2 results.display()
      3 print('%d results found.' % results.count())

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\db\_query.py in display(self, start, stop, figsize)
    138 
    139     def display(self, start=0, stop=10, figsize=None):
--> 140         self.ui.display(start, stop, figsize)
    141 
    142 

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\db\_query.py in display(self, start, stop, figsize)
     35         for index, record in enumerate(self.querySet.query_set[start:stop]):
     36             #tableHTML[index+2] = self.tableRow(index+start, record, figsize)
---> 37             task = asyncio.ensure_future(self.tableRow(index+start, record, figsize))
     38             task.add_done_callback(functools.partial(callback, pos=index))
     39             self._tasks.append(task)

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\tasks.py in ensure_future(coro_or_future, loop)
    517         if loop is None:
    518             loop = events.get_event_loop()
--> 519         task = loop.create_task(coro_or_future)
    520         if task._source_traceback:
    521             del task._source_traceback[-1]

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py in create_task(self, coro)
    280         Return a task object.
    281         """
--> 282         self._check_closed()
    283         if self._task_factory is None:
    284             task = tasks.Task(coro, loop=self)

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py in _check_closed(self)
    355     def _check_closed(self):
    356         if self._closed:
--> 357             raise RuntimeError('Event loop is closed')
    358 
    359     def _asyncgen_finalizer_hook(self, agen):

RuntimeError: Event loop is closed

```

**Comment by Lagikna** [comment]
```py

results = lab.query()
results.display()
print('%d results found.' % results.count())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-8ba9aa32f2d0> in <module>()
      1 results = lab.query()
----> 2 results.display()
      3 print('%d results found.' % results.count())

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\db\_query.py in display(self, start, stop, figsize)
    138 
    139     def display(self, start=0, stop=10, figsize=None):
--> 140         self.ui.display(start, stop, figsize)
    141 
    142 

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\db\_query.py in display(self, start, stop, figsize)
     35         for index, record in enumerate(self.querySet.query_set[start:stop]):
     36             #tableHTML[index+2] = self.tableRow(index+start, record, figsize)
---> 37             task = asyncio.ensure_future(self.tableRow(index+start, record, figsize))
     38             task.add_done_callback(functools.partial(callback, pos=index))
     39             self._tasks.append(task)

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\tasks.py in ensure_future(coro_or_future, loop)
    517         if loop is None:
    518             loop = events.get_event_loop()
--> 519         task = loop.create_task(coro_or_future)
    520         if task._source_traceback:
    521             del task._source_traceback[-1]

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py in create_task(self, coro)
    280         Return a task object.
    281         """
--> 282         self._check_closed()
    283         if self._task_factory is None:
    284             task = tasks.Task(coro, loop=self)

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\asyncio\base_events.py in _check_closed(self)
    355     def _check_closed(self):
    356         if self._closed:
--> 357             raise RuntimeError('Event loop is closed')
    358 
    359     def _asyncgen_finalizer_hook(self, agen):

RuntimeError: Event loop is closed
```
