### ISSUE TITLE
an error about Driver-AlazarTech_Digitizer

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#29]
**System and QuLab version:**

- win7
- Python 3.6.3
- QuLab 0.2.6

**Steps to reproduce:**
- Code:
```python

```

**Expected behavior:**

**Actual behavior:**

- Crash report:
```
Task exception was never retrieved
future: <Task finished coro=<Application.done() done, defined at B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py:177> exception=AlazarTechError("582, Error 'b'ApiBufferOverflow'' happens when calling function 'AlazarWaitNextAsyncBufferComplete'",)>
Traceback (most recent call last):
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 181, in done
    async for data in self.work():
  File "db://id-5ac06f627a6a6d3d144a4c12/lab/apps/codeID5ac06f627a6a6d3d144a4c11.py", line 23, in work
    y = await app.done()
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 181, in done
    async for data in self.work():
  File "db://id-5ac08ad97a6a6d43ec58e358/lab/apps/codeID5ac08ad97a6a6d43ec58e357.py", line 21, in work
    self.settings['repeats']))
  File "B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "db://id-5ac08ad97a6a6d43ec58e358/lab/apps/codeID5ac08ad97a6a6d43ec58e357.py", line 24, in get_Amp
    ch1, ch2 = self.rc['ATS'].getFFT(readout_len, 0, repeats, heterodyne_freq_list)
  File "db://id-5ab8612d7a6a6d62cc1dfba0/lab/drivers/AlazarTech_Digitizer/AlazarTech_Digitizer.py", line 230, in getFFT
    pre, samplesPerRecord-pre, repeats, procces, beforeCapture, timeout)
  File "db://id-5ab8612d7a6a6d62cc1dfba2/lab/drivers/AlazarTech_Digitizer/AlazarTech_Wrapper.py", line 306, in get_Traces_DMA
    self.check_errors(ignores=[589])
  File "db://id-5ab8612d7a6a6d62cc1dfba2/lab/drivers/AlazarTech_Digitizer/AlazarTech_Wrapper.py", line 80, in check_errors
    raise AlazarTechError(errors[-1][0], '%d, %s' % errors[-1])
lab.drivers.AlazarTech_Digitizer.AlazarTech_Wrapper.AlazarTechError: 582, Error 'b'ApiBufferOverflow'' happens when calling function 'AlazarWaitNextAsyncBufferComplete'
```

**Comment by feihoo87** [comment]
Is the ADC work correctly by the program  `AlazarDSO`?

**Comment by Lagikna** [comment]
前面测着也没问题，测时间长了就出错，重启又好了，出现好几次了

**Comment by feihoo87** [comment]
I can not reproduce this error on my system. My `ATSApi.DLL` version is `v5.9.21`.
