### ISSUE TITLE
ATS9360 Driver error

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#32]
**System and QuLab version:**

- win7
- Python 3.6.
- QuLab 0.2.10

**Steps to reproduce:**
- Code:
```python

```

**Expected behavior:**

**Actual behavior:**

- Crash report:
```
Task exception was never retrieved
future: <Task finished coro=<Application.done() done, defined at E:\PYTHON\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py:190> exception=AlazarTechError("579, Error 'b'ApiWaitTimeout'' happens when calling function 'AlazarWaitNextAsyncBufferComplete'",)>
Traceback (most recent call last):
  File "E:\PYTHON\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 193, in done
    async for data in self.work():
  File "db://id-5acdb1833e64aa43fc35d39b/lab/apps/codeID5acdb1833e64aa43fc35d39a.py", line 23, in work
    y = await app.done()
  File "E:\PYTHON\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_app.py", line 193, in done
    async for data in self.work():
  File "db://id-5ac8cc443e64aa3e48abfb5e/lab/apps/codeID5ac8cc443e64aa3e48abfb5d.py", line 21, in work
    self.settings['repeats']))
  File "E:\PYTHON\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "db://id-5ac8cc443e64aa3e48abfb5e/lab/apps/codeID5ac8cc443e64aa3e48abfb5d.py", line 24, in get_Amp
    ch1, ch2 = self.rc['ATS'].getFFT(readout_len, 0, repeats, heterodyne_freq_list)
  File "db://id-5acdb0bf3e64aa3bd005c406/lab/drivers/AlazarTech_Digitizer/AlazarTech_Digitizer.py", line 231, in getFFT
    pre, samplesPerRecord-pre, repeats, procces, beforeCapture, timeout)
  File "db://id-5ac8c1743e64aa3d349424a3/lab/drivers/AlazarTech_Digitizer/AlazarTech_Wrapper.py", line 306, in get_Traces_DMA
    self.check_errors(ignores=[589])
  File "db://id-5ac8c1743e64aa3d349424a3/lab/drivers/AlazarTech_Digitizer/AlazarTech_Wrapper.py", line 80, in check_errors
    raise AlazarTechError(errors[-1][0], '%d, %s' % errors[-1])
lab.drivers.AlazarTech_Digitizer.AlazarTech_Wrapper.AlazarTechError: 579, Error 'b'ApiWaitTimeout'' happens when calling function 'AlazarWaitNextAsyncBufferComplete'
```

**Comment by feihoo87** [comment]
Is ADC triggered correctly？
